{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintRWHILE where

-- pretty-printer generated by the BNF converter

import AbsRWHILE
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
   PDefs id0 cmds id -> prPrec i 0 (concatD [doc (showString "read") , prt 0 id0 , doc (showString ";") , prt 0 cmds , doc (showString "write") , prt 0 id])


instance Print Cmd where
  prt i e = case e of
   SAss id exp -> prPrec i 0 (concatD [prt 0 id , doc (showString "^=") , prt 0 exp])
   SIf exp0 cmds1 cmds exp -> prPrec i 0 (concatD [doc (showString "if") , prt 0 exp0 , doc (showString "then") , prt 0 cmds1 , doc (showString "else") , prt 0 cmds , doc (showString "fi") , prt 0 exp])
   SLoop exp0 cmds1 cmds exp -> prPrec i 0 (concatD [doc (showString "from") , prt 0 exp0 , doc (showString "do") , prt 0 cmds1 , doc (showString "loop") , prt 0 cmds , doc (showString "until") , prt 0 exp])
   SStatus  -> prPrec i 0 (concatD [doc (showString "status")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print Exp where
  prt i e = case e of
   AEq exp0 exp -> prPrec i 1 (concatD [doc (showString "=?") , prt 2 exp0 , prt 2 exp])
   ATl exp -> prPrec i 2 (concatD [doc (showString "tl") , prt 3 exp])
   AHd exp -> prPrec i 2 (concatD [doc (showString "hd") , prt 3 exp])
   ACons exp0 exp -> prPrec i 2 (concatD [doc (showString "cons") , prt 3 exp0 , prt 3 exp])
   AVar id -> prPrec i 3 (concatD [prt 0 id])
   ANil  -> prPrec i 3 (concatD [doc (showString "nil")])


instance Print Val where
  prt i e = case e of
   Cons val0 val -> prPrec i 1 (concatD [doc (showString "cons") , prt 2 val0 , prt 2 val])
   Nil  -> prPrec i 2 (concatD [doc (showString "nil")])



